#!/bin/bash

sudo apt-get install --no-remove --assume-yes aptitude aptitude-doc-en debtags
sudo aptitude install -y git-all
sudo aptitude install -y vim-gnome vim-doc
sudo aptitude install -y python-pip python-virtualenv
sudo aptitude install -y yada yada-doc

git config --global color.ui auto
git config --global core.editor /usr/bin/vim
