#!/bin/bash
set -e

export PYINSTALL_PATH=pyinstaller-1.5.1

. env/bin/activate
export WORKINGDIR=`pwd`
cd pyinstaller
rm -rf dist build
python ${PYINSTALL_PATH}/Configure.py
python ${PYINSTALL_PATH}/Build.py bbpgsql.spec
cd dist
ln -s bbpgsql archivewal
ln -s bbpgsql archivepgsql
cd ${WORKING_DIR}
