#!/bin/sh

if test ${#} != 1
then
    echo "Usage make_dep VERSION_NUMBER"
    exit 1
fi
if test ! -f pyinstaller/dist/bbpgsql
then
    echo "Cannot find built package in './pyintsaller/dist'  Aborting."
    exit 1
fi

export DEB_BUILD_OPTIONS=nostrip

thisdir=`pwd`
if test -d sandbox
then
    echo 'Old sandbox found, removing'
    rm -rf sandbox
fi

pkgdir="sandbox/bbpgsql-${1}"
echo 'Creating sandbox'
mkdir sandbox
echo 'Creating package directory'
mkdir ${pkgdir}
echo 'Copying package file'
cp pyinstaller/dist/bbpgsql ${pkgdir}
echo 'Creating changlog file'
cd ${pkgdir}
yada yada
cd ${thisdir}
echo "Copying template yada files"
debdir=${pkgdir}/debian
cp make_deb_templates/packages ${debdir}
cd ${pkgdir}
yada rebuild
dpkg-buildpackage -b
echo "If the build was successful, the package is now in the sandbox directory"
cd ${thisdir}
ls -l sandbox
