#!/bin/bash
PIP_CACHE_DIR=.pip_cache
set -e
echo $PIP_CACHE_DIR
if [ ! -d $PIP_CACHE_DIR ];  then
        echo "making cache dir"
        mkdir $PIP_CACHE_DIR
fi
pip install -E env -r requirements.txt --download-cache=$PIP_CACHE_DIR
. env/bin/activate
python setup.py develop
