#!/bin/bash
set -e

. env/bin/activate
export WORKINGDIR=`pwd`
cd pyinstaller
rm -rf dist build
python pyinstaller-1.5-rc1/Configure.py
python pyinstaller-1.5-rc1/Build.py bbpgsql.spec
cd dist
ln -s bbpgsql archivewal
ln -s bbpgsql archivepgsql
cd ${WORKING_DIR}
