#! /usr/bin/env python
import sys
from bbpgsql.option_parser import common_parse_args
from bbpgsql.option_parser import common_validate_options_and_args
from optparse import OptionParser
import os

if __name__ == '__main__':
    options, args = common_parse_args()

    common_validate_options_and_args(options, args)

