#! /usr/bin/env python
from bbpgsql.bbpgsql_main import bbpgsql_main

#PYINSTALLER KLUDGES
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
MIMEMultipart
MIMEBase
MIMEText

if __name__ == '__main__':
    bbpgsql_main()
